# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "postgres") %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASS", "anything") %>
  database: <%= ENV.fetch("DBNAME", "h3t") %>
  database_tasks: false

development:
  <<: *default

test:
  <<: *default

sandbox:
  <<: *default

production:
  <<: *default
