remote: &remote
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: a+5Pe+vWUuzp9&KG

local: &local
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *local
  database: h3t_development

test: &test
  <<: *local
  database: h3t_test

production:
  <<: *remote
  database: h3t_production

sandbox:
  <<: *remote
  database: h3t_sandbox

cucumber:
  <<: *test
