development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: h3t_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: h3t_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  <<: *remote
  database: h3t_production

sandbox:
  <<: *remote
  database: h3t_sandbox

cucumber:
  <<: *test

remote: &remote
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: a+5Pe+vWUuzp9&KG
